cms/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('cms.views',
    url(r'^category/(?P<category_slug>.*?)/$', 'pages'),
    url(r'^$', 'pages', name='pages'),
    url(r'^(?P<slug>.*?)/$', 'page', name='page'),
)

germinal/urls.py
from django.conf.urls import patterns, include, url

from surlex.dj import surl

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

from newsletter_custom.views import UpdateSubscriptionViev

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    
    #newsletter with customization
    surl('^newsletter/<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
         '<action=subscribe|update|unsubscribe>/activate/<activation_code:s>/$',
         UpdateSubscriptionViev.as_view(), name='newsletter_update_activate'),
    (r'^newsletter/', include('newsletter.urls')),
    
    
    (r'^pages/', include('cms.urls')),
    (r'^tags/', include('tags.urls')),
    (r'^contact/', include('contact.urls')),
    
    url(r'^$', 'products.views.index', name='home'),
    url(r'^(?P<slug>[\w_-]+)$', 'products.views.details', name='product'),
    url(r'^products/(?P<slug>[\w_-]+)$', 'products.views.query_by_segment', name='segment'),
    url(r'^products/$', 'products.views.products_list', name='products'),
)

if settings.LOCAL:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
# -*- coding: utf-8 -*-

import random, glob, os, shutil
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.template.defaultfilters import slugify
from django.conf import settings

from ckeditor.fields import RichTextField
from easy_thumbnails.fields import ThumbnailerImageField
from adminsortable.models import Sortable
from adminsortable.fields import SortableForeignKey

month_choices = (
    (1, u'Janeiro'), (2, u'Fevereiro'), (3, u'Março'),
    (4, u'Abril'), (5, u'Maio'), (6, u'Junho'), 
    (7, u'Julho'), (8, u'Agosto'), (9, u'Setembro'),
    (10, u'Outubro'), (11, u'Novembro'), (12, u'Dezembro'),
)

class Country(models.Model):
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        verbose_name = u"País"
        verbose_name_plural = u"Países"
    
    name = models.CharField(u'País', max_length=80)
    code = models.CharField(u'Código', max_length=4)

class State(models.Model):
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        verbose_name = u"UF"
    
    country = models.ForeignKey(Country, verbose_name=u"País")
    name = models.CharField(u'Estado', max_length=80)
    acronym = models.CharField(u'Sigla', max_length=4)

class ProductionSys(models.Model):
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        verbose_name = u"Sistema de Produção"
    
    name = models.CharField(u'Nome', max_length=80)

class Producer(models.Model):
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        verbose_name = u"produtor"
        verbose_name_plural = u"produtores"
    
    production_sys = models.ManyToManyField(ProductionSys, null=True, blank=True, verbose_name=u"Sistema de Produção")
    state = models.ForeignKey(State, verbose_name=u"UF")
    country = models.ForeignKey(Country, verbose_name=u"País")
    name = models.CharField(u'Produtor', max_length=160)
    responsible = models.CharField(u'Responsável', null=True, blank=True, max_length=160)
    contact = models.CharField(u'Contato', null=True, blank=True, max_length=160)
    city =  models.CharField(u'Cidade', max_length=160)
    email =  models.EmailField(u'E-mail', null=True, blank=True, max_length=100)
    phone =  models.CharField(u'Telefone', null=True, blank=True, max_length=100)
    website =  models.CharField(u'Website', null=True, blank=True, max_length=100)

class Segment(Sortable):
    def __unicode__(self):
        return u'%s' % self.title
    
    class Meta:
        verbose_name = u"segmento"
    
    def get_absolute_url(self):
        return reverse('segment', kwargs={'slug': self.slug})
      
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        else:
            obj_photo = Segment.objects.get(id=self.id)
            if obj_photo.image and self.image not in [obj_photo.image]:
                for fl in glob.glob("%s/%s*" % (settings.MEDIA_ROOT,obj_photo.image)):
                    os.remove(fl)
            
        super(Segment, self).save()
    
    def delete(self):
        obj_photo = Segment.objects.get(id=self.id)
        super(Segment, self).delete()
        
        if obj_photo.image:
            for fl in glob.glob("%s/%s*" % (settings.MEDIA_ROOT,obj_photo.image)):
                os.remove(fl)
    
    def get_upload_to_image(self, filename):
        ext = filename[-3:].lower()
        if ext == 'peg': ext='jpeg'        
        return 'segments/%s_%s.%s' % (self.slug, datetime.now().strftime('%Y%m%d%H%M%S'), ext)
    
    title = models.CharField(u'Segmento', max_length=160)
    description = models.TextField(u'Descrição', null=True, blank=True)
    slug = models.SlugField(max_length=200)
    image = ThumbnailerImageField(u'Imagem', blank=True, null=True, upload_to = get_upload_to_image, resize_source=dict(size=(250, 250), sharpen=False, crop="scale"))

class Certificate(models.Model):
    def __unicode__(self):
        return u'%s' % self.title
    
    class Meta:
        verbose_name = u"certificado"
    
    title = models.CharField(u'Título', max_length=160)

class Photo(Sortable):
    class Meta(Sortable.Meta):
        verbose_name = u"foto"
    
    def save(self):
        if self.image:
            if self.id:
                obj_photo = Photo.objects.get(id=self.id)
                if self.image not in [obj_photo.image]:
                    for fl in glob.glob("%s/%s*" % (settings.MEDIA_ROOT,obj_photo.image)):
                        os.remove(fl)
            
            super(Photo, self).save()
    
    def delete(self):
        obj_photo = Photo.objects.get(id=self.id)
        super(Photo, self).delete()
        for fl in glob.glob("%s/%s*" % (settings.MEDIA_ROOT,obj_photo.image)):
            os.remove(fl)
    
    def get_upload_to_image(self, filename):
        ext = filename[-3:].lower()
        if ext == 'peg': ext='jpeg'        
        return 'products/%s/%s_%s.%s' % (self.products.slug, datetime.now().strftime('%Y%m%d%H%M%S'), str(random.randint(00000,99999)), ext)
    
    def __unicode__(self):
        return u'%s' % self.image
    
    products = SortableForeignKey('Product')
    image = ThumbnailerImageField(u'Imagem', upload_to = get_upload_to_image, resize_source=dict(size=(800, 600), sharpen=False, crop="scale"))
    title = models.CharField(u'Título', max_length=100, blank=True, null=True)

class ProductActivatedManager(models.Manager):
    def get_queryset(self):
        return super(ProductActivatedManager, self).get_queryset().filter(published=True).order_by('order')

class Product(Sortable):
    def __unicode__(self):
        return u'%s' % self.title
    
    class Meta(Sortable.Meta):
        verbose_name = u"produto"
    
    def save(self, *args, **kwargs):
        if not self.id:
            super(Product, self).save(*args, **kwargs)
            self.slug = slugify(str(self.id) + ' ' + self.title)
        super(Product, self).save(*args, **kwargs)
        
    def delete(self):
        slug = self.slug
        super(Product, self).delete()
        
        dir = '%s/products/%s' % (settings.MEDIA_ROOT, slug)
        
        if os.path.exists(dir):
            shutil.rmtree(dir)
    
    def get_absolute_url(self):
        return reverse('product', kwargs={'slug': self.slug})
    
    def main_photo_set(self):
        photo = self.photo_set.order_by('order')
        return photo[0] if photo else None
    
    owner = models.ForeignKey(User, verbose_name=u"Usuário")
    producer = models.ForeignKey(Producer, verbose_name=u"Produtor")
    segment = models.ManyToManyField(Segment, verbose_name=u"Segmento", null=True, blank=True)
    certificate = models.ManyToManyField(Certificate, null=True, blank=True, verbose_name=u"Certificado")
    
    title = models.CharField(u'Título', max_length=160)
    slug = models.SlugField(max_length=200)
    unit = models.CharField(u'Unidade', max_length=10)
    harvest_from = models.IntegerField(u'Safra (início)', null=True, blank=True, choices=month_choices)
    harvest_until = models.IntegerField(u'Safra  (fim)', null=True, blank=True, choices=month_choices)
    retail_price = models.DecimalField(u'Varejo R$', max_digits=6, decimal_places=2, blank=True, null=True)
    wholesale_price = models.DecimalField(u'Atacado R$', max_digits=6, decimal_places=2, blank=True, null=True)
    description =  RichTextField(verbose_name=u'Descrição', null=True, blank=True)
    characteristics =  RichTextField(verbose_name=u'Características', null=True, blank=True)
    ingredients =  RichTextField(verbose_name=u'Ingredientes', null=True, blank=True)
    nutrition_facts = RichTextField(verbose_name=u'Informações nutricionais', null=True, blank=True)
    
    published = models.BooleanField(u'Publicado', default=True)
    available = models.BooleanField(u'Disponível', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    u''' Managers '''
    objects     = models.Manager()
    activated   = ProductActivatedManager()

products/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.core.exceptions import ObjectDoesNotExist

from models import Product, Segment
from banners.models import Banner

def index(request):
    product_list = Product.activated.all()[:9]
    segment_list = Segment.objects.all().order_by('order')[:3]
    
    template = loader.get_template('products/index.html')
    context = RequestContext(request, {
        'product_list'  : product_list,
        'segment_list'  : segment_list,
    })
    return HttpResponse(template.render(context))


def details(request, slug):
    try:
        product = Product.activated.get(slug=slug)
    except ObjectDoesNotExist:
        product = None
    
    try:
        http_referer = request.environ['HTTP_REFERER']
    except KeyError:
        http_referer = '/'
    
    template = loader.get_template('products/details.html')
    context = RequestContext(request, {
        'product'   : product,
        'http_referer' : http_referer,
    })
    return HttpResponse(template.render(context))

def query_by_segment(request, slug):
    product_list = Product.activated.filter(segment__slug=slug)
    segment = Segment.objects.get(slug=slug)
    
    template = loader.get_template('products/products.html')
    context = RequestContext(request, {
        'product_list'  : product_list,
        'filter'  : segment.title,
    })
    return HttpResponse(template.render(context))

def products_list(request):
    product_list = Product.activated.all()
    
    template = loader.get_template('products/products.html')
    context = RequestContext(request, {
        'product_list'  : product_list,
    })
    return HttpResponse(template.render(context))

templates/products/_product_box.html
{% load thumbnail %}

<div class="col-sm-4 product-list">
	<div class="product-list-description">
		<div class="product-list-img">
			<img src='{{ product.main_photo_set.image|thumbnail_url:"small"|default:"holder.js/140x140" }}'>
		</div>
		<h3>{{ product.title }}</h3>
		<p>
			<b>Peso Líquido:</b> {{ product.unit }}
		</p>
		<p>
			<b>Ingredientes:</b> {{ product.ingredients|striptags|truncatewords:15 }}
		</p>
		<p>
			<b>Características:</b> {{ product.characteristics|striptags|truncatewords:15 }}
		</p>
		<p>
			<b>Produtor:</b> {{ product.producer }}
		</p>
		<p>
			{% for cert in product.certificate.all %}
			{% if forloop.first %} <b>Certificado</b> {% endif %}
			{{ cert.title }}{% if not forloop.last %}, {% endif %}
			{% endfor %}
		</p>
	</div>
	<div>
		<p>
			<a class="btn btn-default" href="{{ product.get_absolute_url }}" role="button" title="Confira!">Ver produto</a>
		</p>
	</div>
</div>

templates/products/details.html
{% extends 'layout.html' %}
{% load thumbnail %}
{% load staticfiles %}

{% block title %} {{ product.title }} {% endblock %}

{% block script %}
<script src="{% static 'products/js/products.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block content %}
{% if not product %}
<div class="row">
    <p>Desculpe, este produto está indisponível ou não existe em nosso banco de dados.</p>
</div>

{% else %}

<div class="germinal-section section-products">
	<div class="container marketing">
		<div class="row" id="nav-products">
		    <div> <a href="{{http_referer}}" title="voltar">&laquo; voltar</a> </div>
		</div>
		<div class="row">
			{% if product.photo_set.count %}
            <div class="col-md-6 col-md-push-6"> <h1>{{ product.title }}</h1> </div>
            <div class="col-md-6 col-md-pull-6">
                {% for photo in product.photo_set.all %}
                <div class="tn_photo" id="tn_photo_{{photo.id}}">
                    <img width="auto" height="auto" src="{{ photo.image|thumbnail_url:'gallery-small'|default:'holder.js/40x40' }}" title="{{photo.title}}" alt="{{photo.title}}">
                    <input type="hidden" id="url_img_{{photo.id}}" value="{{ photo.image|thumbnail_url:'large'|default:'holder.js/500x375' }}"/>
                </div>
                {% endfor %}
            </div>
            
            {% else %}
            <div class="col-md-6"> <h1>{{ product.title }}</h1> </div>
            {% endif %}
		</div>
		
		<div class="row">
            {% if product.photo_set.count %}
            <div class="col-sm-6">
                <img id="large-image" class="img-responsive" width="auto" height="auto" />
                <p id="image-description"> </p>
            </div>
            {% endif %}
            
            
            <div class="col-sm-6">
                <p>
					<b>Peso Líquido:</b> {{ product.unit }}
				</p>
				<p>
					<b>Produtor:</b> {{ product.producer }}
				</p>
				<p>
					{% for cert in product.certificate.all %}
					{% if forloop.first %} <b>Certificado</b> {% endif %}
					{{ cert.title }}{% if not forloop.last %}, {% endif %}
					{% endfor %}
				</p>
				<p>
					{% for segment in product.segment.all %}
					{% if forloop.first %} <b>Segmentos:</b> {% endif %}
					{{ segment.title }}{% if not forloop.last %}, {% endif %}
					{% endfor %}
				</p>
				{% if product.harvest_from %}
				<p>
					<b>Safra:</b>
					{{ product.get_harvest_from_display }} à {{ product.get_harvest_until_display }}
				</p>
				{% endif %}
			</div>
			
			{% autoescape off %}
			{% if product.characteristics %}
			<div class="col-sm-6">
				<div class="description">
					<h2>Características</h2> 
					{{ product.characteristics }}
				</div>
			</div>
			{% endif %}
			
			{% if product.ingredients %}
			<div class="col-sm-6">
				<div class="description">
                	<h2> Ingredientes</h2>
                	{{ product.ingredients }}
                </div>
            </div>
            {% endif %}
            
            {% if product.nutrition_facts %}
			<div class="col-sm-6">
                <div class="description">
                	<h2> Informações Nutricionais </h2>
                	{{ product.nutrition_facts }}
                </div>
            </div>
            {% endif %}
            
            {% if product.description %}
			<div class="col-sm-6">
                <div class="description">
                	<h2> Descrição </h2>
                	{{ product.description }}
                </div>
            </div>
            {% endif %}
            
            {% endautoescape %}
        </div>
	</div>
</div>

{% endif %}

{% endblock %}

templates/products/index.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load banner %}
{% load cms_pages %}

{% block title %} Início {% endblock %}

{% block top %}
{% generate_banner 'principal' %}
{% endblock %}

{% block content %}

<div class="germinal-section section-segment">
	<div class="container marketing">
		<!-- Thrsel -->
		<div class="row">
			{% for segment in segment_list %}
			<div class="col-sm-4 segment-list">
				<div class="segment-list-description">
					<img class="img-circle" src='{{ segment.image|thumbnail_url:"small"|default:"holder.js/140x140" }}'>
					<h2>{{ segment.title }}</h2>
					<p>
						{{ segment.description|default:"" }}
					</p>
				</div>
				<div>
					<p>
						<a class="btn btn-default" href="{{ segment.get_absolute_url }}" role="button">Ver produtos</a>
					</p>
				</div>
			</div>
			{% if forloop.counter|divisibleby:"3" %}
		</div>
		<div class="row">
			{% endif %}
			{% endfor %}
		</div><!-- /.row -->
	</div>
</div>

<div class="germinal-section section-products">
	<div class="container marketing">

		<div class="row">
			{% for product in product_list %}
			
			{% include "products/_product_box.html" %}
			
			{% if forloop.counter|divisibleby:"3" %}
		</div>
		<div class="row">
			{% endif %}

			{% empty %}

			<p>
				Em breve publicaremos os produtos disponíveis, aguardem!
			</p>

			{% endfor %}
		</div>
	</div><!-- /.container -->
</div>

<div class="germinal-section section-institutional">
	<div class="container marketing">
		{% list_pages 'principios' %}
	</div>
</div>

{% endblock %}

templates/products/products.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load banner %}
{% load cms_pages %}

{% block title %} Início {% endblock %}

{% block content %}

<div class="germinal-section section-institutional">
	<div class="container marketing">
		<h1>
			<a href="/products/" title="ver todos os produtos">Produtos</a>
			{% if filter %} / {{ filter }} {% endif %}
		</h1>
		<div class="row">
			{% for product in product_list %}
			{% include "products/_product_box.html" %}
			{% if forloop.counter|divisibleby:"3" %}
		</div>
		<div class="row">
			{% endif %}

			{% empty %}
			
			<div class="col-md-12">
				<p>
					Em breve publicaremos os produtos disponíveis, aguardem!
				</p>
			</div>

			{% endfor %}
		</div>
	</div><!-- /.container -->
</div>

{% endblock %}